name: ess_source
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
  - pyg
dependencies:
  # Riemannian FM
  - python==3.10.16
  - pytorch==2.2.0
  - pytorch-cuda==12.1
  - igl==2.2.1
  - meshplot==0.4.0
  - pip
  # - geopandas==0.14.3
  - geopandas==1.0.1
  # CDVAE
  - ase==3.24.0
  - conda-forge::nglview==3.1.4
  - seaborn
  - conda-forge::joblib==1.4.2
  # ours
  - conda-forge::yaml==0.2.5
  - conda-forge::pymatgen==2023.10.11
  - pip:
    # Riemannian FM
    - submitit==1.5.1
    - pre-commit==4.1.0
    - black==25.1.0
    - ipykernel==6.29.5
    - torchdiffeq==0.2.5
    - scikit-learn==1.6.1
    - pytorch-lightning==2.5.0.post0
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - hydra_colorlog==1.2.0
    - click==8.1.8
    - wandb
    - git+https://github.com/geoopt/geoopt.git@v0.5.1
    - biopython==1.85
    - pyevtk==1.6.0
    - ipympl==0.9.7
    - matplotlib
    - jupyter==1.1.1
    - numpy==1.26.4
    - pandas==2.2.3
    - tqdm==4.67.1
    - torchmetrics==1.6.3
    # CDVAE
    - smact==3.0.2
    - pytest==8.3.5
    - python-dotenv==1.0.1
    - p-tqdm==1.4.2
    # DiffCSP
    - pyshtools==4.13.1  # versions ~4.11 fail to build
    - pyxtal==1.0.6
    - chemparse==0.3.2
    - einops==0.8.1
    # ours
    - ratelimit==2.2.1
    - matbench-discovery==1.0.0
    - pymatviz==0.15.1
    - chgnet==0.3.8
    - toolz==1.0.0
    - POT==0.9.5
    - e3nn==0.5.5
    - mp-api==0.45.3
    - matminer==0.9.3
    - -e remote/cdvae
    - -e remote/DiffCSP-official
    - -e remote/riemannian-fm
    - -e .
    # from here below, we use find-links
    - --find-links https://data.pyg.org/whl/torch-2.2.0+cu121.html
    - pyg_lib
    - torch_geometric
    - torch_scatter 
    - torch_sparse 
    - torch_cluster 
    - torch_spline_conv
    - --find-links https://data.dgl.ai/wheels/torch-2.2/cu121/repo.html
    - dgl
    # alignn for property prediction
    - alignn
